import { NextPage } from 'next'
import React, { useState } from "react"
import MessageList from '../components/MessagesList';
import SendMessageForm from '../components/SendMessageForm';
import Title from '../components/Title';
import { useRouter } from 'next/router';
import Head from 'next/head'


const DUMMY_DATA = [
    {
        senderId: "Goose",
        text: "Hey.",
        currentUser: false
    },
    {
        senderId: "BarBar",
        text: "What's up?",
        currentUser: false
    }
]

export default function ChatRoom() {

    const router = useRouter();

    const username = router.query.user;

    const [messages, setMessages] = useState(DUMMY_DATA);

    const sendMessage = (inputText) => {
        const newMessage = {
            senderId: `${username}`,
            text: `${inputText}`,
            currentUser: true
        }
        setMessages((messages) => [...messages, newMessage]);
    }

    return (
        <div className="app">
            <Head>
                <title>Scratch Chat</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
                <link href="https://fonts.googleapis.com/css2?family=Abel&family=Bebas+Neue&family=Montserrat&display=swap" rel="stylesheet"></link>
            </Head>

            <main className="main">
            
            <Title />
            <div className="chat-room">
                <MessageList messages={messages} />
                <SendMessageForm 
                    sendMessage={sendMessage}
                />
            </div>

            </main>

            <footer className="footer">
                <h2>SCRATCH CHAT</h2>
            </footer>
        
        </div>
    )
}



;