import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import { SignUp } from '../components/login'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Scratch Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Abel&family=Bebas+Neue&family=Montserrat&display=swap" rel="stylesheet"></link>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to SCRATCH CHAT
        </h1>

        <SignUp /> 

      </main>

      <footer className={styles.footer}>
        <h2>SCRATCH CHAT</h2>
      </footer>
    </div>
  )
}
