import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import { SignUp } from '../components/login'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Scratch Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image className={styles.logo} src="pizza_queen.png"/>
        <h1 className={styles.title}>
          Welcome to SCRATCH CHAT
        </h1>

        <SignUp /> 

      </main>

      <footer className={styles.footer}>
        <h2>SCRATCH CHAT</h2>
      </footer>
    </div>
  )
}
